"""Added wishlist feature

Revision ID: ba11e54c43f2
Revises: 29afae8c97fc
Create Date: 2024-06-25 18:25:09.822027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba11e54c43f2'
down_revision: Union[str, None] = '29afae8c97fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_description', table_name='products')
    op.drop_index('ix_products_title', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.drop_column('products', 'title')
    op.drop_column('products', 'price')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.add_column('products', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('products', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('ix_products_title', 'products', ['title'], unique=False)
    op.create_index('ix_products_description', 'products', ['description'], unique=False)
    # ### end Alembic commands ###
